name: Sync
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Branch we want to sync'
        required: true
        default: 'staging'
        options:
          - 'master'
          - 'staging'
          - 'develop'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Setup git
        run: |
          git config user.name ${{ secrets.BOT_ACCESS_NAME }} 
          git config user.email ${{ secrets.BOT_ACCESS_EMAIL }} 
      - name: Sync branch
        run: |
          git checkout ${{ github.ref_name }};
          git pull;
          git checkout ${{ github.event.inputs.target }};
          git pull;
          git rebase ${{ github.ref_name }};
          git push;