name: Version and Tag
on:
  push:
    branches:
      - master

jobs:
  version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Setup git
        run: |
          git config user.name ${{ secrets.BOT_ACCESS_NAME }} 
          git config user.email ${{ secrets.BOT_ACCESS_EMAIL }} 
      - name: Install dependencies
        run: yarn
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        run: npx semantic-release
      - name: Sync Branches
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        run: | 
          git pull;
          git checkout staging;
          git pull;
          git rebase master;
          git push --force
          git checkout develop;
          git pull;
          git rebase staging;
          git push --force